#!/usr/bin/env bash


prefix="module_swarm_logs_$2"

if [[ "module_swarm_logs_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_ekg_elasticsearch_volume
	fi
	
if [[ "module_swarm_logs_ekg_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_ekg_grafana_volume
	fi
	
if [[ "module_swarm_logs_ingest_container_logs_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_ingest_container_logs_filebeat_volume
	fi
	
if [[ "module_swarm_logs_kz_kafka_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_kz_kafka_secrets_volume
	fi
	
if [[ "module_swarm_logs_kz_kafka_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_kz_kafka_data_volume
	fi
	
if [[ "module_swarm_logs_kz_zookeeper_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_kz_zookeeper_secrets_volume
	fi
	
if [[ "module_swarm_logs_kz_zookeeper_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_kz_zookeeper_data_volume
	fi
	
if [[ "module_swarm_logs_kz_zookeeper_log_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_kz_zookeeper_log_volume
	fi
	
if [[ "module_swarm_logs_metrics_monitor_heartbeat_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_metrics_monitor_heartbeat_data_volume
	fi
	
if [[ "module_swarm_logs_metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_metrics_monitor_heartbeat_monitors_volume
	fi
	
if [[ "module_swarm_logs_processor_streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_swarm_logs_processor_streamsets_volume
	fi
	
if [[ "module_swarm_logs_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v module_swarm_logs_ekg_elasticsearch_volume:/usr/share/elasticsearch/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/ekg_elasticsearch_volume.tar
		fi
		
if [[ "module_swarm_logs_metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v module_swarm_logs_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /modeco/volumes/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		fi
		
if [[ "module_swarm_logs_processor_streamsets_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v module_swarm_logs_processor_streamsets_volume:/data ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/processor_streamsets_volume.tar
		fi
		
